apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: template-pvc
  namespace: template-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      system : traindb
      subsystem : ml
      podtype : pv
      name : template-pv
